### ISSUE TITLE
Error when calling munch

### ISSUE THREAD

**Issue by iamdriz** [jmrocela/munchjs#23]
@jmrocela 

If I run:

```
cd /Users/Cameron/Desktop/munch
Cameron:munch cameron$ munch --view Scale.html --js Grid.js
```

I get the following errors:

```
fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './usage'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.exports.run (/usr/local/lib/node_modules/munch/munch.js:859:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/munch/bin/munch:7:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
Cameron:munch cameron$ 
```

**Comment by iamdriz** [comment]
Any updates on this? Thanks.

**Comment by luixxiul** [comment]
+1 @jmrocela

**Comment by amqex** [comment]
@iamdriz I am also getting this exact error

**Comment by arlusf** [comment]
You can copy the usage file to the folder you run the munch command from. Or modify munch.js (refer to the fork commit)
The path to these files on my system was:
C:\Documents and Settings\yourname\Application Data\npm\node_modules\munch

**Comment by jmrocela** [comment]
been busy lately. @arlusf maybe put a pull request in?

**Comment by arlusf** [comment]
ok
